/* ══════════════════════════════════════════════════════════════
   Dava Konuları — Yargı Birimine Göre
   Her mahkeme türü için UYAP uyumlu, kapsamlı dava konuları listesi.
   Alfabetik sıralıdır.
   ══════════════════════════════════════════════════════════════ */

export const DAVA_KONULARI: Record<string, string[]> = {

  // ═══════════════════════════════════════════════════════════
  //  HUKUK YARGI BİRİMLERİ
  // ═══════════════════════════════════════════════════════════

  'AİLE MAHKEMESİ': [
    'Aile Konutu Şerhi',
    'Aile Konutu Şerhi Kaldırılması',
    'Ailenin Korunmasına Dair Kanun Gereği Tedbir',
    'Babalık Davası',
    'Boşanma (Anlaşmalı)',
    'Boşanma (Çekişmeli)',
    'Çocuk Mallarının Korunması',
    'Çocukla Kişisel İlişki Kurulması',
    'Eşler Arası Alacak',
    'Evlat Edinme',
    'Evlat Edinme İlişkisinin Kaldırılması',
    'Evlenme İzni',
    'Evlenmenin Butlanı (Mutlak)',
    'Evlenmenin Butlanı (Nisbi)',
    'Evlenmenin Feshi',
    'Evliliğin İptali',
    'İddet Müddetinin Kaldırılması',
    'İştirak Nafakası',
    'İştirak Nafakası (Artırım)',
    'İştirak Nafakası (Kaldırılması)',
    'Katkı Payı Alacağı',
    'Katılma Alacağı',
    'Kişisel İlişkinin Değiştirilmesi',
    'Kişisel İlişkinin Kaldırılması',
    'Mal Paylaşımı',
    'Mal Rejimi Değişikliği',
    'Mal Rejiminin Tasfiyesi',
    'Nafaka (Artırım)',
    'Nafaka (Kaldırılması)',
    'Nişan Bozulması Nedeniyle Tazminat',
    'Soybağının Reddi',
    'Soybağının Tespiti',
    'Tanıma',
    'Tanımanın İptali',
    'Tedbir Nafakası',
    'Velayet Değiştirilmesi',
    'Velayet Düzenlenmesi',
    'Velayet Kaldırılması',
    'Yoksulluk Nafakası',
    'Yoksulluk Nafakası (Artırım)',
    'Yoksulluk Nafakası (Kaldırılması)',
    'Ziynet Alacağı',
  ],

  'ASLİYE HUKUK MAHKEMESİ': [
    'Ad ve Soyadı Değişikliği',
    'Alacak',
    'Araç Değer Kaybı',
    'Arsa Payı Düzeltilmesi',
    'Cins Tahsisi',
    'Çaplı Taşınmaz Tescili',
    'Destekten Yoksun Kalma Tazminatı',
    'Ecrimisil (Haksız İşgal Tazminatı)',
    'El Atmanın Önlenmesi',
    'Gaiplik Kararı',
    'Geçit Hakkı Tesisi',
    'Haksız Fiil Tazminatı',
    'Haksız İhtiyati Haciz Tazminatı',
    'Haksız İhtiyati Tedbir Tazminatı',
    'İpotek Terkini',
    'İrtifak Hakkı Tesisi',
    'İstihkak',
    'İstirdat',
    'İtirazın İptali',
    'Kamulaştırma Bedelinin Tespiti ve Tescil',
    'Kamulaştırmasız El Atma',
    'Kat İrtifakı Kurulması',
    'Kat Mülkiyetine Geçiş',
    'Kayıt Düzeltme',
    'Komşuluk Hukukundan Kaynaklanan Tazminat',
    'Mecra Hakkı Tesisi',
    'Menfi Tespit',
    'Mülkiyet Tespiti',
    'Müdahalenin Men\'i',
    'Nüfus Kaydının Düzeltilmesi',
    'Ortaklığın Giderilmesi (İzale-i Şüyu)',
    'Ön Alım (Şufa) Hakkı',
    'Sözleşmeden Kaynaklanan Alacak',
    'Sözleşmenin Feshi',
    'Şahsi Hakkın Tespiti',
    'Şerh',
    'Tapu İptali ve Tescil',
    'Tapu Kaydında Düzeltme',
    'Taşınmaz Satış Vaadi',
    'Tazminat (Maddi)',
    'Tazminat (Maddi ve Manevi)',
    'Tazminat (Manevi)',
    'Tazminat (Trafik Kazası)',
    'Tespit',
    'Trafik Kazası Nedeniyle Alacak',
    'Tüzel Kişiliğin Sona Erdirilmesi',
    'Usulsüz Tebligat Şikayeti',
    'Vakıf Tescili',
    'Yaş Düzeltme',
    'Zilyetlik',
    'Zilyetliğin Korunması',
  ],

  'ASLİYE TİCARET MAHKEMESİ': [
    'Alacak (Cari Hesap)',
    'Banka Kredi Sözleşmesinden Kaynaklanan Alacak',
    'Çek İptali',
    'Çek Tazminatı',
    'Deniz Ticareti Uyuşmazlığı',
    'Fatura Alacağı',
    'Haksız Rekabet',
    'Haksız Rekabet Tazminatı',
    'İflas',
    'İflas Erteleme',
    'İflasın Kaldırılması',
    'İhtiyati Haciz',
    'İhtiyati Tedbir',
    'İtirazın İptali (Ticari)',
    'Kasko Alacağı',
    'Konkordato',
    'Kooperatif Aidat Alacağı',
    'Kooperatif Ortaklıktan Çıkarma İptali',
    'Kooperatif Üyelik Tespiti',
    'Kooperatif Uyuşmazlığı',
    'Limited Şirket Çıkma/Çıkarılma',
    'Limited Şirket Müdür Azli',
    'Menfi Tespit (Ticari)',
    'Marka Hakkına Tecavüzün Önlenmesi',
    'Marka Tescil İptali',
    'Navlun Alacağı',
    'Ortaklığın Feshi',
    'Pay Devri',
    'Sigorta Alacağı',
    'Sigorta Rücu Alacağı',
    'Sigorta Tazminatı',
    'Şirket Birleşme/Bölünme',
    'Şirket Genel Kurul Kararı İptali',
    'Şirket Ortaklığından Çıkarılma',
    'Tasfiye Memuru Atanması',
    'Ticari Alacak',
    'Ticari Satımdan Kaynaklanan Alacak',
    'Ticari Sözleşmeden Kaynaklanan Alacak',
    'Trafik Sigorta Alacağı',
    'TTK Sorumluluk Davası',
    'Yönetim Kurulu Kararı İptali',
  ],

  'BAM Hukuk Dairesi (İlk Derece)': [
    'Hakimlerin Hukuki Sorumluluğu',
    'Tazminat (Devlet Aleyhine)',
  ],

  'Bölge Adliye Mah. Hukuk Dairesi': [
    'İstinaf Başvurusu',
  ],

  'FİKRİ VE SINAİ HAKLAR HUKUK MAHKEMESİ': [
    'Coğrafi İşaret İhlali',
    'Endüstriyel Tasarım İhlali',
    'Faydalı Model Tecavüzü',
    'Fikir ve Sanat Eseri İhlali',
    'Haksız Rekabet (Fikri Mülkiyet)',
    'Lisans Sözleşmesi Uyuşmazlığı',
    'Marka Hakkına Tecavüzün Önlenmesi',
    'Marka Hükümsüzlüğü',
    'Marka Tescil Başvurusuna İtiraz',
    'Patent Hükümsüzlüğü',
    'Patent Tecavüzünün Tespiti ve Önlenmesi',
    'Tazminat (Fikri Mülkiyet İhlali)',
    'Telif Hakkı İhlali',
    'Ticaret Unvanına Tecavüz',
  ],

  'İCRA HUKUK MAHKEMESİ': [
    'Borcun İtfası / Zamanaşımı İtirazı',
    'Haciz İhbarnamesine İtiraz',
    'İcra Emrine İtiraz',
    'İcra İflas Kanunu Gereği Şikayet',
    'İcra Takibinin İptali/Taliki',
    'İhalenin Feshi',
    'İhtiyati Haciz',
    'İmzaya İtiraz',
    'İstihkak',
    'İstihkak (Üçüncü Kişi)',
    'İtirazın Kaldırılması',
    'İtirazın Kaldırılması ve Tahliye',
    'Kambiyo Hukuku Şikayeti',
    'Kıymet Takdirine İtiraz',
    'Meskeniyet İddiası',
    'Sıra Cetveline İtiraz',
    'Şikayet (İcra Müdürlüğü İşlemi)',
    'Tahliye',
    'Takibin İptali',
    'Tasarrufun İptali',
  ],

  'İŞ MAHKEMESİ': [
    'AGİ Alacağı',
    'Bakiye Süre Ücreti',
    'Eşit Davranma İlkesine Aykırılık',
    'Fazla Mesai Ücreti',
    'Genel Tatil Ücreti',
    'Hafta Tatili Ücreti',
    'Hizmet Tespiti',
    'İhbar Tazminatı',
    'İkramiye Alacağı',
    'İş Kazası Nedeniyle Maddi Tazminat',
    'İş Kazası Nedeniyle Manevi Tazminat',
    'İş Sözleşmesinin Geçersizliği',
    'İşçi Alacağı',
    'İşçilik Alacağı (Toplu)',
    'İşe İade',
    'Kıdem Tazminatı',
    'Kötüniyet Tazminatı',
    'Meslek Hastalığı Nedeniyle Tazminat',
    'Mobbing Tazminatı',
    'Prim Alacağı',
    'Rekabet Yasağı',
    'Rücu Alacağı (SGK)',
    'Sendikal Tazminat',
    'SGK İşlem İptali',
    'SGK Prim Borcu',
    'Toplu İş Sözleşmesi Uyuşmazlığı',
    'Ücret Alacağı',
    'Yıllık İzin Ücreti',
  ],

  'KADASTRO MAHKEMESİ': [
    'Kadastro Komisyon Kararına İtiraz',
    'Kadastro Sonrası Tapu İptali ve Tescil',
    'Kadastro Tespitine İtiraz',
    'Mera Tahsis İptali',
    'Orman Kadastrosuna İtiraz',
    'Sınır Uyuşmazlığı',
    'Taşınmaz Tescili',
    'Tespite İtiraz',
    'Zilyetliğe Dayalı Tescil',
  ],

  'KADASTRO MAHKEMESİ (MÜS)': [
    'Kadastro Tespitine İtiraz',
    'Müstakil Kadastro İşlemi',
    'Tescil',
  ],

  'SULH HUKUK MAHKEMESİ': [
    'Delil Tespiti',
    'Elbirliği Mülkiyetinin Paylı Mülkiyete Çevrilmesi',
    'Kat Mülkiyeti Uyuşmazlığı',
    'Kayyım Atanması',
    'Kayyım Kararının Kaldırılması',
    'Kira Alacağı',
    'Kira Bedelinin Tespiti',
    'Kira Sözleşmesinin Feshi',
    'Kira Uyarlanması',
    'Mirasçılık Belgesi Verilmesi',
    'Mirasçılık Belgesinin İptali',
    'Miras Ortaklığına Temsilci Atanması',
    'Miras Payının Devri',
    'Mirasın Reddi',
    'Ortaklığın Giderilmesi (İzale-i Şüyu)',
    'Tahliye (Kiralanan)',
    'Terekenin Tespiti',
    'Terekeye Temsilci Atanması',
    'Vasiyetnamenin Açılması',
    'Vasiyetnamenin İptali',
    'Vasiyetnamenin Tenfizi',
    'Vesayet',
    'Vesayet Altına Alma',
    'Vesayetin Kaldırılması',
    'Vasi Atanması',
    'Vasi Değiştirilmesi',
    'Yasal Danışman Atanması',
  ],

  'TÜKETİCİ MAHKEMESİ': [
    'Abonelik Sözleşmesinden Kaynaklanan Alacak',
    'Ayıplı Hizmet',
    'Ayıplı Mal',
    'Banka/Finans Kuruluşu Uyuşmazlığı',
    'Cayma Hakkı Kullanımı',
    'Devre Mülk Sözleşmesi İptali',
    'Devre Tatil Sözleşmesi İptali',
    'Eksik İfa',
    'Garanti Kapsamında Onarım/Değişim',
    'Haksız Şart',
    'Konut Satışından Kaynaklanan Alacak',
    'Kredi Kartı Uyuşmazlığı',
    'Kredi Masraf İadesi',
    'Mesafeli Satış Sözleşmesi İptali',
    'Paket Tur Sözleşmesi Uyuşmazlığı',
    'Sigorta Uyuşmazlığı (Tüketici)',
    'Taksitli Satış Sözleşmesi Uyuşmazlığı',
    'Tüketici Alacağı',
    'Tüketici Hakem Heyeti Kararına İtiraz',
    'Tüketici Sözleşmesinin İptali',
  ],

  // ═══════════════════════════════════════════════════════════
  //  CEZA YARGI BİRİMLERİ
  // ═══════════════════════════════════════════════════════════

  'AĞIR CEZA MAHKEMESİ': [
    'Anayasal Düzene Karşı Suçlar',
    'Banka ve Kredi Kartlarının Kötüye Kullanılması (Nitelikli)',
    'Casusluk',
    'Cinsel İstismar',
    'Cinsel Saldırı (Nitelikli)',
    'Devlet Sırlarına Karşı Suçlar',
    'Fuhuş (Örgütlü)',
    'Hırsızlık (Nitelikli)',
    'Hileli İflas',
    'İhaleye Fesat Karıştırma',
    'İnsan Ticareti',
    'İrtikap',
    'İşkence',
    'Kasten Öldürme',
    'Kasten Öldürmeye Teşebbüs',
    'Nitelikli Dolandırıcılık',
    'Örgüt Kurma / Yönetme',
    'Örgüt Üyeliği',
    'Resmi Belgede Sahtecilik (Nitelikli)',
    'Rüşvet',
    'Silahlı Gasp',
    'Suç İşlemek Amacıyla Örgüt Kurma',
    'Terörle Mücadele Kanunu Kapsamında Suçlar',
    'Uyuşturucu Madde İmal ve Ticareti',
    'Uyuşturucu Madde Kullanılmasını Kolaylaştırma',
    'Yağma (Gasp)',
    'Zimmet',
  ],

  'ASLİYE CEZA MAHKEMESİ': [
    'Basit Dolandırıcılık',
    'Belgede Sahtecilik',
    'Bilişim Suçları',
    'Bina İçinde Hırsızlık',
    'Çocuğun Kaçırılması ve Alıkonulması',
    'Dolandırıcılık',
    'Görevi Kötüye Kullanma',
    'Güveni Kötüye Kullanma',
    'Hak Kullanımını ve Beslenmeyi Engelleme',
    'Hırsızlık',
    'İş ve Çalışma Hürriyetinin İhlali',
    'Karşılıksız Çek Keşide Etme',
    'Kasten Yaralama',
    'Kasten Yaralama (Silahla)',
    'Kişilerin Huzur ve Sükununu Bozma',
    'Kişiyi Hürriyetinden Yoksun Kılma',
    'Konut Dokunulmazlığının İhlali',
    'Mala Zarar Verme',
    'Özel Belgede Sahtecilik',
    'Özel Hayatın Gizliliğini İhlal',
    'Resmi Belgede Sahtecilik',
    'Suç Eşyasını Satın Alma veya Kabul Etme',
    'Suçluyu Kayırma',
    'Şantaj',
    'Tehdit',
    'Trafik Güvenliğini Tehlikeye Sokma',
    'Uyuşturucu Madde Kullanma',
    'Yaralama (Bilinçli Taksir)',
    'Yaralama (Taksirle)',
  ],

  'Bölge Adliye Mah. Ceza Dairesi': [
    'İstinaf Başvurusu (Ceza)',
  ],

  'ÇOCUK AĞIR CEZA MAHKEMESİ': [
    'Cinsel İstismar (Çocuk Sanık)',
    'Hırsızlık (Nitelikli — Çocuk Sanık)',
    'Kasten Öldürme (Çocuk Sanık)',
    'Kasten Öldürmeye Teşebbüs (Çocuk Sanık)',
    'Nitelikli Dolandırıcılık (Çocuk Sanık)',
    'Uyuşturucu Madde İmal ve Ticareti (Çocuk Sanık)',
    'Yağma (Çocuk Sanık)',
  ],

  'ÇOCUK MAHKEMESİ': [
    'Çocuğa Yönelik Koruyucu/Destekleyici Tedbir',
    'Dolandırıcılık (Çocuk Sanık)',
    'Güveni Kötüye Kullanma (Çocuk Sanık)',
    'Hırsızlık (Çocuk Sanık)',
    'Kasten Yaralama (Çocuk Sanık)',
    'Konut Dokunulmazlığını İhlal (Çocuk Sanık)',
    'Mala Zarar Verme (Çocuk Sanık)',
    'Tehdit (Çocuk Sanık)',
    'Uyuşturucu Madde Kullanma (Çocuk Sanık)',
  ],

  'FİKRİ VE SINAİ HAKLAR CEZA MAHKEMESİ': [
    'Bandrol Yükümlülüğüne Aykırılık',
    'Endüstriyel Tasarım Hakkı İhlali',
    'Marka Hakkına Tecavüz',
    'Patent Hakkına Tecavüz',
    'Telif Hakkı İhlali (Ceza)',
    'Ticari Sır İhlali',
  ],

  'İCRA CEZA HAKİMLİĞİ': [
    'Alacaklıyı Zarara Uğratmak Kastıyla Mevcudu Eksiltme',
    'Borçlunun Ödeme Şartını İhlali',
    'Çocuk Teslimi Emrine Muhalefet',
    'Gerçeğe Aykırı Mal Beyanı',
    'Nafaka Hükmüne Uymamak',
    'Ticareti Terk Hükümlerine Muhalefet',
  ],

  'İNFAZ HAKİMLİĞİ': [
    'Adli Para Cezası İtirazı',
    'Ceza İnfaz Kurumu Disiplin Cezası İtirazı',
    'Cezanın Ertelenmesi Talebi',
    'Denetimli Serbestlik İhlali',
    'Denetimli Serbestlik Talebi',
    'Hükümlü Nakil Talebi',
    'İnfaz Durdurma Talebi',
    'Koşullu Salıverilme',
    'Koşullu Salıverilmenin Geri Alınması',
    'Müddetname İtirazı',
    'Özel İnfaz Usulü Talebi',
  ],

  'İSTİNAF CEZA DAİRESİ (İLK DERECE)': [
    'Hakimlerin Cezai Sorumluluğu',
  ],

  'SULH CEZA HAKİMLİĞİ': [
    'Adli Kontrol',
    'Basit Tıbbi Müdahale ile Giderilebilir Yaralama',
    'Basit Yaralama',
    'Bilişim Suçları (Basit)',
    'Çevreye Zarar Verme',
    'El Koyma Kararına İtiraz',
    'Gürültüye Neden Olma',
    'Hakaret',
    'Hükmün Açıklanmasının Geri Bırakılması İtirazı',
    'İdari Para Cezasına İtiraz',
    'İşyeri Kapatma Kararına İtiraz',
    'Kabahat (İdari Yaptırım)',
    'Kişilerin Huzur ve Sükununu Bozma',
    'Konut Dokunulmazlığının İhlali (Basit)',
    'Mala Zarar Verme',
    'Özel Hayatın Gizliliğini İhlal (Basit)',
    'Soruşturma İzni',
    'Tehdit (Basit)',
    'Tutukluluk İncelemesi',
    'Uzlaştırma Sonrası İşlemler',
  ],

  'YARGITAY CEZA DAİRESİ (İLK DERECE)': [
    'Yüce Divan Yargılaması',
  ],

  // ═══════════════════════════════════════════════════════════
  //  İDARİ YARGI BİRİMLERİ
  // ═══════════════════════════════════════════════════════════

  'İDARE MAHKEMESİ': [
    'Askeri İşlem İptali',
    'Atama İşleminin İptali',
    'Belediye Encümen Kararı İptali',
    'Belediye Meclis Kararı İptali',
    'Çevre İzni İptali',
    'Diploma Denklik İşlemi İptali',
    'Disiplin Cezası İptali',
    'Emeklilik İşlemi İptali',
    'Görevde Yükselme Sınavı İptali',
    'Gümrük İşlemi İptali',
    'Güvenlik Soruşturması İptali',
    'İdari İşlemin İptali',
    'İdari Para Cezası İptali',
    'İdari Sözleşmeden Kaynaklanan Uyuşmazlık',
    'İhale İptali',
    'İhale İşlemi İptali',
    'İmar Planı İptali',
    'İmar Uygulaması İptali',
    'İntibak İşleminin İptali',
    'İptal Davası (Genel)',
    'İskan İzni İptali',
    'Kamulaştırma İşlemi İptali',
    'Kamu Görevlisi İşlem İptali',
    'Lisans İşlemi İptali',
    'Maden Ruhsatı İptali',
    'Meslekten Çıkarma İptali',
    'Nakil İşleminin İptali',
    'Öğrenci İşleri İptali',
    'Pasaport İşlemi İptali',
    'Ruhsat İptali',
    'Sınav Sonucu İptali',
    'Tam Yargı Davası',
    'Tam Yargı Davası (Tazminat)',
    'Yıkım Kararı İptali',
    'Yurt Dışı Çıkış Yasağı İptali',
  ],

  'VERGİ MAHKEMESİ': [
    'Düzeltme Şikayet Başvurusu Reddi',
    'Ecrimisil İhbarnamesine İtiraz',
    'Ek Tahakkuka İtiraz',
    'Emlak Vergisi İptali',
    'Gümrük Vergisi İptali',
    'Harç Tahakkuku İptali',
    'İhtirazi Kayıtla Verilen Beyanname',
    'Katma Değer Vergisi Tarhiyatı İptali',
    'Motorlu Taşıtlar Vergisi İptali',
    'Ödeme Emrinin İptali',
    'Özel Tüketim Vergisi İptali',
    'Para Cezası İptali (Vergi)',
    'Stopaj Vergisi İptali',
    'Uzlaşma Sonrası İtiraz',
    'Vergi / Ceza İhbarnamesi İptali',
    'Vergi Cezası İptali',
    'Vergi İnceleme Raporuna İtiraz',
    'Vergi Mahsup Talebi',
    'Vergi Tarhiyatının İptali',
    'Vergi Ziyaı Cezası İptali',
  ],

  'BÖLGE İDARE MAHKEMESİ': [
    'İstinaf Başvurusu (İdari)',
    'İstinaf Başvurusu (Vergi)',
    'İtiraz (İdari Yaptırım)',
  ],

  // ═══════════════════════════════════════════════════════════
  //  DİĞER YARGI BİRİMLERİ
  // ═══════════════════════════════════════════════════════════

  'Savcılık': [
    'Ceza Soruşturması',
    'Kovuşturmaya Yer Olmadığına Dair Karara İtiraz',
    'Soruşturma',
    'Şikayet',
    'Uzlaştırma',
  ],

  'Tazminat Komisyonu Başkanlığı': [
    'AİHM Kararı Gereği Tazminat',
    'Anayasa Mahkemesi Bireysel Başvuru Tazminatı',
    'Makul Sürede Yargılanma Hakkı İhlali Tazminatı',
    'Uzun Tutukluluk Tazminatı',
  ],
};

// ── Yardımcı: Tüm konuları düz liste olarak al ──
export function tumDavaKonulari(): string[] {
  const set = new Set<string>();
  for (const konular of Object.values(DAVA_KONULARI)) {
    for (const konu of konular) {
      set.add(konu);
    }
  }
  return [...set].sort((a, b) => a.localeCompare(b, 'tr'));
}

// ── Yardımcı: Birden fazla yargı birimi için birleşik konular ──
export function davaKonulariByBirimler(birimler: string[]): string[] {
  const set = new Set<string>();
  for (const birim of birimler) {
    const konular = DAVA_KONULARI[birim];
    if (konular) {
      for (const konu of konular) {
        set.add(konu);
      }
    }
  }
  return [...set].sort((a, b) => a.localeCompare(b, 'tr'));
}
